version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # RabbitMQ messaging port
      - "15672:15672" # RabbitMQ management UI
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  backend:
    build: ./backend
    container_name: flask-backend
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
    ports:
      - "5001:5001"

  consumer:
    build: ./consumer
    container_name: consumer-service
    privileged: true
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
